// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Translation2d;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 

    public static final class TurretConstants {
        public static final int SENSOR_TO_MECH_RATIO = 10;

        public static final double MAX_LEFT_POSITION = -0.25;
        public static final double MAX_RIGHT_POSITION = 0.25;
        public static final double NEUTRAL_POSITION = 0;
        public static final double MAX_LEFT_DEGREES = MAX_LEFT_POSITION * 360;
        public static final double MAX_RIGHT_DEGREES = MAX_RIGHT_POSITION * 360;

        public static final double TURRET_CAM_TIMEOUT = 0.5;
        
        public static final double degreesToRotations(double degrees) {
            return degrees / 360;
        }

        public static final double rotationsToDegrees(double rotations) {
            return rotations * 360;
        }
    }

    public static final class VisionConstants {
        public static final String TURRET_CAM = "limelight-turret";
        public static final double ANGLE_ERROR_THRESHOLD = 3.0; // degrees
    }

    public static final class FieldConstants {
        public static final AprilTagFields APRIL_TAG_FIELD = AprilTagFields.k2026RebuiltAndymark;
        public static final AprilTagFieldLayout APRIL_TAG_FIELD_LAYOUT = AprilTagFieldLayout
            .loadField(APRIL_TAG_FIELD);

        public static final double BLUE_HUB_CENTER_x = APRIL_TAG_FIELD_LAYOUT.getTagPose(5).get().getX();
        public static final double BLUE_HUB_CENTER_Y = APRIL_TAG_FIELD_LAYOUT.getTagPose(10).get().getY();
        public static final Translation2d BLUE_HUB_CENTER = new Translation2d(BLUE_HUB_CENTER_x, BLUE_HUB_CENTER_Y);

        public static final double RED_HUB_CENTER_x = APRIL_TAG_FIELD_LAYOUT.getTagPose(21).get().getX();
        public static final double RED_HUB_CENTER_Y = APRIL_TAG_FIELD_LAYOUT.getTagPose(20).get().getY();
        public static final Translation2d RED_HUB_CENTER = new Translation2d(RED_HUB_CENTER_x, RED_HUB_CENTER_Y);

    }
}