// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import java.util.Optional;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static final class VisionConstants {
        
        public static final AprilTagFields APRIL_TAG_FIELD = AprilTagFields.k2026RebuiltAndymark;
        public static final AprilTagFieldLayout APRIL_TAG_FIELD_LAYOUT = AprilTagFieldLayout
            .loadField(APRIL_TAG_FIELD);

        public static final double FIELD_WIDTH_METERS = APRIL_TAG_FIELD_LAYOUT.getFieldWidth();
        public static final double FIELD_LENGTH_METERS = APRIL_TAG_FIELD_LAYOUT.getFieldLength();

        // This variable assumes the robot is a square
        public static final double ROBOT_WIDTH_METERS = 0.5;

        public static final String LIMELIGHT_NAME = "limelight";
        public static final double[] CAMERA_POSE_ROBOT_SPACE = {
                0.4, // X position of camera on robot in meters
                0.0, // Y position of camera on robot in meters
                0.5, // Z position of camera on robot in meters
                0.0, // Roll of the camera on the robot in degrees
                0.0, // Pitch of the camera on the robot in degrees
                0.0  // Yaw of the camera on the robot in degrees
        };

        public static final int[] TAGS_FOR_AUTO_ALIGNMENT = {15, 16, 31, 32};

        // Currently Excluded: 20, 21, 24
        public static final int[] TAGS_FOR_POSE_ESTIMATION = {
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19,
            22, 23, 25, 26, 27, 28, 29, 30,
            31, 32
        };

        
   }

   public static final class Debug {
        public static final boolean DEBUG_MODE = true;
        public static final boolean INTAKE_ROLLER_EXISTS = true;
        public static final boolean INTAKE_EXTEND_EXISTS = true;
        public static final boolean SHOOTER_SPEED_OVERRIDE = true;
    }

    public static final class DriveConstants {

        public static final Alliance MyAlliance() {
            Optional<Alliance> ally = DriverStation.getAlliance();
            if (ally.isPresent()) {
                return ally.get() == Alliance.Red ? Alliance.Red : Alliance.Blue;
            } else {
                return null;
            }
        }
    }

}