// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Amps;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix6.hardware.TalonFX;

import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;

/**
 *
 */
public class Turrent extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public TalonFX rotateShooterMotor;

    public DigitalInput zeroSwitch;
    public DigitalOutput led;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final MotionMagicVoltage m_motionMagicVoltage = new MotionMagicVoltage(0).withSlot(0);

    double maxLeftPosition = -0.25;
    double maxRightPosition = 0.25;
    double neutralPosition = 0;
    double maxLeftDegrees = maxLeftPosition * 360;
    double maxRightDegrees = maxRightPosition * 360;

    /**
    *
    */
    public Turrent() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        rotateShooterMotor = new TalonFX(23, "rio");

        TalonFXConfiguration configs = new TalonFXConfiguration();
        configs.Slot0.kP = 2.4; // An error of 1 rotation results in 2.4 V output
        configs.Slot0.kI = 0; // No output for integrated error
        configs.Slot0.kD = 0.1; // A velocity of 1 rps results in 0.1 V output
        // Peak output of 8 V
        configs.Voltage.withPeakForwardVoltage(Volts.of(8))
                .withPeakReverseVoltage(Volts.of(-8));

        configs.Slot1.kP = 60; // An error of 1 rotation results in 60 A output
        configs.Slot1.kI = 0; // No output for integrated error
        configs.Slot1.kD = 6; // A velocity of 1 rps results in 6 A output
        // Peak output of 120 A
        configs.TorqueCurrent.withPeakForwardTorqueCurrent(Amps.of(120))
                .withPeakReverseTorqueCurrent(Amps.of(-120));

        /* Retry config apply up to 5 times, report if failure */
        StatusCode status = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            status = rotateShooterMotor.getConfigurator().apply(configs);
            if (status.isOK())
                break;
        }
        if (!status.isOK()) {
            System.out.println("Could not apply configs, error code: " + status.toString());
        }
        configs.SoftwareLimitSwitch.ForwardSoftLimitEnable = true;
        configs.SoftwareLimitSwitch.ForwardSoftLimitThreshold = 5; // 5 rotations
        configs.SoftwareLimitSwitch.ReverseSoftLimitEnable = true;
        configs.SoftwareLimitSwitch.ReverseSoftLimitThreshold = 0; // 0 rotations
        rotateShooterMotor.getConfigurator().apply(configs);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        zeroSwitch = new DigitalInput(2);
        addChild("zeroSwitch", zeroSwitch);

        led = new DigitalOutput(8);
        addChild("led", led);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putNumber("Rotation", rotateShooterMotor.getPosition().getValueAsDouble());
        SmartDashboard.putBoolean("Zero?", zeroSwitch.get());

        var table = NetworkTableInstance.getDefault().getTable("Limelight");
        double tx = table.getEntry("tx").getDouble(0.0);
        double tv = table.getEntry("tv").getDouble(0.0);

        if (tv > 0.5) {
            double targetPosition = 2.5 + (tx / 36.0);
            rotateShooterMotor.setControl(m_motionMagicVoltage.withPosition(targetPosition));
        } else {

        }

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void spinRight() {
        led.set(true);
        if (SmartDashboard.getNumber("Rotation", 0) < 5) {
            rotateShooterMotor.set(.04);
        } else {
            rotateShooterMotor.set(0);
        }

    }

    public void spinLeft() {
        if (SmartDashboard.getNumber("Rotation", 0) > 0) {
            rotateShooterMotor.set(-.04);
        } else {
            rotateShooterMotor.set(0);
        }
    }

    public void spinStop() {
        rotateShooterMotor.set(0);
    }

    public void aim(double degrees) {
        degrees = Math.max(maxLeftDegrees, degrees);
        degrees = Math.min(maxRightDegrees, degrees);
        rotateShooterMotor
                .setControl(m_motionMagicVoltage.withPosition(Constants.TurretConstants.degreesToRotations(degrees)));
    }

    public Command checkZeroLeft() {
        return run(() -> {
            if (zeroSwitch.get()) {
                rotateShooterMotor.setPosition(maxLeftPosition);
            } else {
                rotateShooterMotor.set(-0.05);
            }
        })
                .until(() -> zeroSwitch.get())

                .finallyDo(() -> {
                    rotateShooterMotor.setControl(m_motionMagicVoltage.withPosition(neutralPosition));
                });
    }
}
